# rules
#- colon
#- control_statement
#- file_length
#- force_cast
#- function_body_length
#- leading_whitespace
#- line_length
#- nesting
#- operator_whitespace
#- return_arrow_whitespace
#- todo
#- trailing_newline
#- variable_name_max_length
#- variable_name_min_length
#- type_body_length
#- variable_name


disabled_rules:
- trailing_whitespace
- type_name
- force_cast
- variable_name
- trailing_newline


line_length: 200

excluded:
- Pods
- Carthage

type_body_length:
- 300 # warning
- 500 # error

variable_name_min_length:
- 3 # warning
- 0 # error

variable_name_max_length:
- 60 # warning
- 80 # error

function_body_length:
- 100 # warning
- 200 # error